#!/bin/bash

# This is a sample script to be configured and copied in /etc/init.d
# to mount a file system using yas3fs at boot

# Those are some environmental variables to configure yas3fs

UNPRIVILEGED_USER=ec2-user
YAS3FS_PATH=/opt/yas3fs
BUCKET_NAME=your_bucket
BUCKET_PATH=can_be_empty
TOPIC_ARN=arn:... # You can get the topic ARN From the SNS web console
REGION=eu-west-1 # The default if empty is us-east-1
MOUNT_PATH=/mnt/shared # Use whatever you like here...

# source function library
. /etc/rc.d/init.d/functions

start()
{
	su $UNPRIVILEGED_USER -c "$YAS3FS_PATH/yas3fs --url=s3://$BUCKET_NAME/$BUCKET_PATH --topic $TOPIC_ARN --new-queue --region $REGION $MOUNT_PATH"
}

stop()
{
	su  -c "fusermount -zu $MOUNT_PATH"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
esac

